image: node:8.12.0
pipelines:
  branches:
    master:
      - step:
          deployment: production
          caches:
            - node
            - npm
          script:
            - npm install
            - npm install -g firebase-tools quasar-cli
            - quasar build
            - firebase deploy --token=$FIREBASE_TOKEN --project supernova-admin-panel --non-interactive --only hosting

definitions:
  caches:
    firebase-tools: vendor/bundle
